[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "agenet"
description = "Auto-grader for Git-based programming exercises"
version = "0.0.3"
authors = [ { name = "Chathuranga Basanyaka", email = "chathurangab@sltc.ac.lk" } ]
readme = "README.md"
requires-python = ">=3.8"
keywords = [
    "aat",
    "education",
    "autograder",
    "programming",
    "computer science education" ]
license = {text = "GPL-3"}
# https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX",
    "Topic :: Education" ]
dependencies = [
    "python-dateutil",
    "pyyaml",
    "requests",
    "sh >= 2.0.0",
    "yarl",
    "validators" ]



[project.optional-dependencies]
dev = [
    "numpy", "pandas", "tabulate", "matplotlib", "scipy" ]


