site_name: agenet
site_url: https://cahthuranag.github.io/agenet/
repo_url: https://github.com/cahthuranag/agenet
edit_uri: https://github.com/cahthuranag/agenet/tree/main/docs
site_description: Documentation for age of information calculation toolbox
site_author: Chathuranga Basanayaka
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="CC-BY License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>

theme:
  name: material
  custom_dir: overrides
  logo: https://github.com/clugen/.github/blob/main/logos/apple-touch-icon-120x120.png?raw=true
  favicon: https://raw.githubusercontent.com/clugen/.github/main/logos/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    accent: deep orange
  features:
  - navigation.instant
  - navigation.expand
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - toc.integrate

plugins:
- search
- gallery:
    examples_dirs: docs/examples
    gallery_dirs: docs/generated/gallery
    within_subsection_order: FileNameSortKey
    run_stale_examples: true
    reset_modules: []
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        options:
          docstring_style: google
          show_root_toc_entry: false
          show_submodules: no
          heading_level: 2
          line_length: 80
          show_signature_annotations: true
          separate_signature: true

watch:
  - ../agenet

nav:
- Home: index.md
- Theory: theory.md
#- Examples: generated/gallery
#- Reference: reference.md
#- Development: dev.md

markdown_extensions:
- admonition
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
    guess_lang: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.arithmatex:
    generic: true
- toc:
    toc_depth: 2
    permalink: true

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js