site_name: agenet documention
site_url: https://cahthuranag.github.io/agenet
repo_url: https://github.com/cahthuranag/agenet
edit_uri: https://github.com/cahthuranag/agenet/edit/master/docs/docs/
site_description: Documentation for age of information calculation toolbox
site_author: Chathuranga Basanayaka
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="CC-BY License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>

theme:
  name: material
  #custom_dir: overrides
  logo: https://raw.githubusercontent.com/cahthuranag/agenet/main/docs/docs/image/logo.png
  favicon: https://raw.githubusercontent.com/cahthuranag/agenet/main/docs/docs/image/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    accent: deep orange
  features:
  - navigation.instant
  - navigation.expand
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - toc.integrate
nav:
- Home: index.md
#- Theory: theory.md
- "Reference": reference.md
- "Usage": usage.md
- "Development": dev.md

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
