name: Docs

on:
  push:
    tags: 'v*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build docs
        run: |
          pip3 install --upgrade pip
          pip3 install .[dev]
          cd docs
          mkdocs build
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/site
permissions:
  contents: write