# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
    branches: [main]
    paths: [ 'agenet/**', 'tests/**', 'pyproject.toml' ]
  push:
    branches: [main]
    paths: [ 'agenet/**', 'tests/**', 'pyproject.toml' ]
    tags: '*'

jobs:
  run-tests:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['3.8', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Setup latest Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        pip install pip --upgrade
        pip install .[dev]
    - name: Test with pytest
      run: pytest